name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Django) — Lint & Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # dev tools
          pip install flake8 black pytest pytest-django

      - name: Lint (flake8)
        run: flake8 .

      - name: Lint (black check)
        run: black --check .

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
          # Use sqlite in CI for speed unless your tests need Postgres
          DATABASE_URL: sqlite:///ci.sqlite3
        run: pytest -q

  frontend:
    name: Frontend (React) — Lint & Typecheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (eslint)
        run: npm run lint --if-present

      - name: Typecheck (tsc)
        run: npm run typecheck --if-present

      - name: Build (vite)
        run: npm run build --if-present
